image:
  file: .gitpod.Dockerfile

ports:
  # Laravel server
  - port: 8080
    onOpen: open-preview
  # MySQL server
  - port: 3306
    onOpen: ignore
  # Mailhog UI
  - port: 8025
    onOpen: notify

tasks:
  - init: >
      mysql -u root -e "create database example_app" &&
      cp .env.example .env &&
      sed -i "s|APP_URL=|APP_URL=${GITPOD_WORKSPACE_URL}|g" .env &&
      sed -i "s|APP_URL=https://|APP_URL=https://8000-|g" .env &&
      composer install &&
      npm i &&
      php artisan key:generate
    command: >
      php artisan serve --port=8080
  # Start MailHog
  - command: mailhog -api-bind-addr 127.0.0.1:8025 -ui-bind-addr 127.0.0.1:8025 -smtp-bind-addr 127.0.0.1:1025
    
